### ISSUE TITLE
Better slides template

### ISSUE THREAD

**Issue by Amasus** [Voting-Rights-Code/Equitable-Polling-Locations#16]
## Problem:
Current slide deck template very boring. (https://docs.google.com/presentation/d/1Qjqnhj7OLI55vWAf4Q5yh2ZKomSeQ7MVLpJ3Tfg4mVM/edit?usp=sharing)

## Desired outcome: 
A more colorful slide deck that "pops"

## Output specifications:
1. Slide template
   1. Slide deck must be in a template format saved on Google slides
   1. Template must include a logo on each slide
1. Sample slides for presentation of work
   1. Must include logo on each slide
   2. No place holder images
   3. Better images for contributors?
   4. Needs a discussion about how long this should be / how much of it is about the organization an how much about the work
       1. It is okay for different people to have different positions on this. @Amasus  has a preference to get to the work fast when she presents. Other people may want a longer organizational intro before talking about the product. Whatever the case, this should be discussed to make the vision of the person writing the slide deck outline and the person giving the talk match (or at least not collide)

## Status:
There is a current draft of a slide deck made by @abd1tus (https://docs.google.com/presentation/d/1wmgWysBj1PhrsXQWkrqU3ULV60GA42KeIpRdzZpk3TQ/edit?usp=sharing) available on google drive. This needs to be adjusted before it is ready to be used in presentations.

**Comment by abd1tus** [comment]
Tasks:

**Slide template**

- [*] Slide deck must be in a template format saved on Google slides
- [*] Template must include a logo on each slide

**Sample slides for presentation of work**

- [ ] Must include logo on each slide
- [ ] No place holder images
- [ ] Better images for contributors?

**Comment by abd1tus** [comment]
The template I had made has now been updated with the above requested changes. 

(Renamed to "VRC Slide Template") 

https://docs.google.com/presentation/d/1wmgWysBj1PhrsXQWkrqU3ULV60GA42KeIpRdzZpk3TQ/edit#slide=id.g2b4845cb30b_0_0

It can be used in other slide decks by going to the menu in google slides:

- View -> Theme Builder -> Import Theme Button (bottom right corner) 
- Choose "VRC Slide Template"

**Comment by abd1tus** [comment]
Waiting on better contributor images.

**Comment by abd1tus** [comment]
Updated [Data Viz/ Eng open mic slides](https://docs.google.com/presentation/d/1SQyCxzGsY_0E_0sHVocx76_8iWaXfipS1y3k2oyQxxg/edit#slide=id.p).
