### ISSUE TITLE
Driving distances (table version)

### ISSUE THREAD

**Issue by Amasus** [Voting-Rights-Code/Equitable-Polling-Locations#17]
# This task has been refactored into other tasks.   Only here for reference.

## Problem

Until the driving distance server is up, driving distances will be computed locally by @dskipper.

## Necessary inputs

1. File with colums orgin_id  origin_lat, origin_long
2. File columms destination_id destination_lat, destination_long

## Desired outputs

1. File wtih columns origin_id, destination_id, distance, first_node_lat, first_node_long, last_node_lat, last_node_long
    1. The last four columns are the lat /long coords of the first node used by the map to compute driving distance and the last node used. 
    2. This is not necessary for the Equitable Polling Locations algorithm, but is desired by @Amasus for analysis

## Steps to implement

1. Write a function that, takes in county name as input and creates the two input files indicated above.
2. Modify the build_data function to incorporate the driving distance output.
3. @dskipper How much extra work does pulling the first and last node coordinates take? Is this a reasonable ask? I know it is a thing one can get from the open street map API, but I don't know how you have it set up.
   1. Discuss this point and omit if not feasible

**Comment by dskipper** [comment]
Daphne Skipper liked your email
